"""CadQuery execution endpoint."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from fastapi import APIRouter

from cadforge_engine.domain.sandbox import execute_cadquery
from cadforge_engine.models.requests import CadQueryRequest
from cadforge_engine.models.responses import CadQueryResponse

router = APIRouter(prefix="/tools")


def _save_source_code(
    project_root: Path,
    code: str,
    output_name: str,
    output_path: Path,
) -> Path:
    """Save the CadQuery source code alongside the exported model."""
    scripts_dir = project_root / "output" / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    script_path = scripts_dir / f"{output_name}.py"

    header = (
        f'"""CadQuery script: {output_name}\n'
        f"\n"
        f"Generated by CadForge on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}\n"
        f"Output: {output_path.name}\n"
        f'"""\n\n'
        f"import cadquery as cq\n"
        f"import numpy as np\n\n"
    )

    if "import cadquery" in code or "from cadquery" in code:
        full_code = code
    else:
        full_code = header + code

    script_path.write_text(full_code, encoding="utf-8")
    return script_path


@router.post("/cadquery", response_model=CadQueryResponse)
async def execute_cadquery_endpoint(req: CadQueryRequest) -> CadQueryResponse:
    """Execute CadQuery code and optionally export the result."""
    project_root = Path(req.project_root)

    if req.format == "step":
        output_dir = project_root / "output" / "step"
        output_path = output_dir / f"{req.output_name}.step"
    else:
        output_dir = project_root / "output" / "stl"
        output_path = output_dir / f"{req.output_name}.stl"

    output_dir.mkdir(parents=True, exist_ok=True)

    result = execute_cadquery(req.code, output_path=output_path)

    if not result.success:
        return CadQueryResponse(
            success=False,
            error=result.error,
            stdout=result.stdout,
            stderr=result.stderr,
        )

    response = CadQueryResponse(
        success=True,
        stdout=result.stdout,
    )

    if result.has_workpiece:
        script_path = _save_source_code(project_root, req.code, req.output_name, output_path)
        response.output_path = str(output_path)
        response.script_path = str(script_path)
        response.message = (
            f"Model exported to {output_path}\n"
            f"Source code saved to {script_path}"
        )
    else:
        response.message = "Code executed successfully (no result variable set)"

    return response
