"""Tests for CadQuery tool handler — specifically source code saving."""

from __future__ import annotations

from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest

from cadforge.cad.sandbox import SandboxResult
from cadforge.tools.cadquery_tool import _save_source_code, handle_execute_cadquery


class TestSaveSourceCode:
    def test_saves_script(self, tmp_project: Path):
        output_path = tmp_project / "output" / "stl" / "cube.stl"
        script_path = _save_source_code(
            tmp_project,
            code="result = cq.Workplane().box(50, 50, 50)",
            output_name="cube",
            output_path=output_path,
        )
        assert script_path.exists()
        assert script_path.name == "cube.py"
        content = script_path.read_text()
        assert "cq.Workplane().box(50, 50, 50)" in content

    def test_adds_header_when_no_import(self, tmp_project: Path):
        output_path = tmp_project / "output" / "stl" / "model.stl"
        script_path = _save_source_code(
            tmp_project,
            code="result = cq.Workplane().box(10, 10, 10)",
            output_name="model",
            output_path=output_path,
        )
        content = script_path.read_text()
        assert "import cadquery as cq" in content
        assert "import numpy as np" in content
        assert "Generated by CadForge" in content

    def test_no_header_when_import_exists(self, tmp_project: Path):
        output_path = tmp_project / "output" / "stl" / "model.stl"
        code = "import cadquery as cq\nresult = cq.Workplane().box(10, 10, 10)"
        script_path = _save_source_code(
            tmp_project,
            code=code,
            output_name="model",
            output_path=output_path,
        )
        content = script_path.read_text()
        # Should not duplicate the import
        assert content.count("import cadquery") == 1

    def test_saves_in_scripts_dir(self, tmp_project: Path):
        output_path = tmp_project / "output" / "stl" / "test.stl"
        script_path = _save_source_code(
            tmp_project, "x = 1", "test", output_path
        )
        assert "scripts" in str(script_path)
        assert script_path.parent.name == "scripts"

    def test_output_name_in_header(self, tmp_project: Path):
        output_path = tmp_project / "output" / "stl" / "bracket.stl"
        script_path = _save_source_code(
            tmp_project, "result = 1", "bracket", output_path
        )
        content = script_path.read_text()
        assert "bracket" in content


class TestHandleExecuteCadqueryWithSave:
    @patch("cadforge.tools.cadquery_tool.execute_cadquery")
    def test_saves_script_on_success(self, mock_exec, tmp_project: Path):
        mock_exec.return_value = SandboxResult(
            success=True,
            result="mock_workpiece",
            stdout="",
            variables={"result": "mock_workpiece"},
        )
        result = handle_execute_cadquery(
            {"code": "result = cq.Workplane().box(10, 10, 10)", "output_name": "box"},
            tmp_project,
        )
        assert result["success"] is True
        assert "script_path" in result
        assert Path(result["script_path"]).exists()

    @patch("cadforge.tools.cadquery_tool.execute_cadquery")
    def test_no_script_on_failure(self, mock_exec, tmp_project: Path):
        mock_exec.return_value = SandboxResult(
            success=False,
            error="SyntaxError",
            stdout="",
            stderr="bad code",
        )
        result = handle_execute_cadquery(
            {"code": "invalid(", "output_name": "bad"},
            tmp_project,
        )
        assert result["success"] is False
        assert "script_path" not in result

    @patch("cadforge.tools.cadquery_tool.execute_cadquery")
    def test_no_script_without_workpiece(self, mock_exec, tmp_project: Path):
        mock_exec.return_value = SandboxResult(
            success=True,
            result=None,
            stdout="hello",
            variables={"x": 42},
        )
        result = handle_execute_cadquery(
            {"code": "x = 42", "output_name": "nomodel"},
            tmp_project,
        )
        assert result["success"] is True
        assert "script_path" not in result

    @patch("cadforge.tools.cadquery_tool.execute_cadquery")
    def test_message_includes_both_paths(self, mock_exec, tmp_project: Path):
        mock_exec.return_value = SandboxResult(
            success=True,
            result="wp",
            stdout="",
            variables={"result": "wp"},
        )
        result = handle_execute_cadquery(
            {"code": "result = 1", "output_name": "part"},
            tmp_project,
        )
        assert "output_path" in result
        assert "script_path" in result
        assert "Source code saved" in result["message"]
